[package]
name = "rlgym-learn"
version = "1.1.0"
edition = "2021"
readme = "README.md"
license="Apache-2.0"

[lib]
name = "_rlgym_learn"
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = "1.22.0"
fastrand = "2.2.0"
itertools = "0.13.0"
numpy = "0.28.0"
pyany-serde = { path = "/home/jpk/Coding/GitHub/pyany-serde" }
pyo3 = { version = "0.28.3", features = ["py-clone"] }
pyo3-stub-gen = { path = "/home/jpk/Coding/GitHub/pyo3-stub-gen/pyo3-stub-gen" }
pyo3-stub-gen-derive = { path = "/home/jpk/Coding/GitHub/pyo3-stub-gen/pyo3-stub-gen-derive" }
raw_sync = "0.1.5"
rkyv = "0.8.10"
shared_memory = "0.12.4"

[[bin]]
name = "stub_gen"
doc = false

[features]
rl = []
