# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import datetime
import enum
import typing

import numpy
import numpy.typing
import rlgym.api
import rlgym.rocket_league.api
from rlgym.api import (
    ActionSpaceType,
    ActionType,
    AgentID,
    EngineActionType,
    ObsSpaceType,
    ObsType,
    RewardType,
    RLGym,
    StateType,
)

__all__ = [
    "AgentManager",
    "CarPythonSerde",
    "EnvAction",
    "EnvActionResponse",
    "EnvActionResponseType",
    "EnvProcessInterface",
    "GameConfigPythonSerde",
    "GameStatePythonSerde",
    "InitStrategy",
    "NumpySerdeConfig",
    "PhysicsObjectPythonSerde",
    "PickleableInitStrategy",
    "PickleableNumpySerdeConfig",
    "PickleablePyAnySerdeType",
    "PyAnySerdeType",
    "Timestep",
    "env_process_fn",
    "euler_to_quaternion",
    "euler_to_rotation",
    "quaternion_to_euler",
    "quaternion_to_rotation",
    "recvfrom_byte",
    "rotation_to_euler",
    "rotation_to_quaternion",
    "sendto_byte",
]

@typing.final
class AgentManager:
    def __new__(
        cls,
        agent_controllers: collections.abc.Sequence[typing.Any],
        batched_tensor_action_associated_learning_data: builtins.bool,
    ) -> AgentManager: ...
    def get_env_actions(
        self,
        env_obs_data_dict: collections.abc.Mapping[
            builtins.str,
            tuple[
                collections.abc.Sequence[typing.Any],
                collections.abc.Sequence[typing.Any],
            ],
        ],
        state_info: collections.abc.Mapping[builtins.str, typing.Any],
    ) -> dict: ...

@typing.final
class CarPythonSerde:
    def __new__(
        cls, *args: typing.Any, agent_id_serde_type: PyAnySerdeType | None = None
    ) -> CarPythonSerde: ...
    def __getstate__(self) -> builtins.list[builtins.int]: ...
    def __setstate__(self, state: collections.abc.Sequence[builtins.int]) -> None: ...
    def append(
        self,
        buf: typing.Any,
        offset: builtins.int,
        obj: rlgym.rocket_league.api.Car[rlgym.api.AgentID],
    ) -> builtins.int: ...
    def get_bytes(
        self,
        start_addr: builtins.int | None,
        obj: rlgym.rocket_league.api.Car[rlgym.api.AgentID],
    ) -> bytes: ...
    def retrieve(
        self, buf: typing.Any, offset: builtins.int
    ) -> tuple[rlgym.rocket_league.api.Car[rlgym.api.AgentID], builtins.int]: ...

class EnvAction:
    @typing.final
    class STEP(EnvAction):
        __match_args__ = (
            "shared_info_setter_option",
            "send_state",
            "action_list",
            "action_associated_learning_data",
        )
        @property
        def shared_info_setter_option(self) -> typing.Any | None: ...
        @property
        def send_state(self) -> builtins.bool: ...
        @property
        def action_list(self) -> list[ActionType]: ...
        @property
        def action_associated_learning_data(self) -> typing.Any: ...
        def __new__(
            cls,
            shared_info_setter_option: typing.Any | None,
            send_state: builtins.bool,
            action_list: list,
            action_associated_learning_data: typing.Any,
        ) -> EnvAction.STEP: ...

    @typing.final
    class RESET(EnvAction):
        __match_args__ = (
            "shared_info_setter_option",
            "send_state",
        )
        @property
        def shared_info_setter_option(self) -> typing.Any | None: ...
        @property
        def send_state(self) -> builtins.bool: ...
        def __new__(
            cls, shared_info_setter_option: typing.Any | None, send_state: builtins.bool
        ) -> EnvAction.RESET: ...

    @typing.final
    class SET_STATE(EnvAction):
        __match_args__ = (
            "desired_state",
            "shared_info_setter_option",
            "send_state",
            "prev_timestep_id_dict_option",
        )
        @property
        def desired_state(self) -> typing.Any: ...
        @property
        def shared_info_setter_option(self) -> typing.Any | None: ...
        @property
        def send_state(self) -> builtins.bool: ...
        @property
        def prev_timestep_id_dict_option(self) -> typing.Any | None: ...
        def __new__(
            cls,
            desired_state: typing.Any,
            shared_info_setter_option: typing.Any | None,
            send_state: builtins.bool,
            prev_timestep_id_dict_option: typing.Any | None,
        ) -> EnvAction.SET_STATE: ...

    ...

class EnvActionResponse:
    @property
    def enum_type(self) -> EnvActionResponseType: ...
    @property
    def shared_info_setter(self) -> typing.Any | None: ...
    @property
    def desired_state(self) -> typing.Any | None: ...
    @property
    def prev_timestep_id_dict(self) -> typing.Any | None: ...
    @typing.final
    class STEP(EnvActionResponse):
        __match_args__ = (
            "shared_info_setter",
            "send_state",
        )
        @property
        def shared_info_setter(self) -> typing.Any | None: ...
        @property
        def send_state(self) -> builtins.bool: ...
        def __new__(
            cls,
            shared_info_setter: typing.Any | None = None,
            send_state: builtins.bool = False,
        ) -> EnvActionResponse.STEP: ...

    @typing.final
    class RESET(EnvActionResponse):
        __match_args__ = (
            "shared_info_setter",
            "send_state",
        )
        @property
        def shared_info_setter(self) -> typing.Any | None: ...
        @property
        def send_state(self) -> builtins.bool: ...
        def __new__(
            cls,
            shared_info_setter: typing.Any | None = None,
            send_state: builtins.bool = False,
        ) -> EnvActionResponse.RESET: ...

    @typing.final
    class SET_STATE(EnvActionResponse):
        __match_args__ = (
            "desired_state",
            "shared_info_setter",
            "send_state",
            "prev_timestep_id_dict",
        )
        @property
        def desired_state(self) -> typing.Any: ...
        @property
        def shared_info_setter(self) -> typing.Any | None: ...
        @property
        def send_state(self) -> builtins.bool: ...
        @property
        def prev_timestep_id_dict(self) -> typing.Any | None: ...
        def __new__(
            cls,
            desired_state: typing.Any,
            shared_info_setter: typing.Any | None = None,
            send_state: builtins.bool = False,
            prev_timestep_id_dict: typing.Any | None = None,
        ) -> EnvActionResponse.SET_STATE: ...

@typing.final
class EnvProcessInterface:
    def __new__(
        cls,
        agent_id_serde: PyAnySerdeType,
        action_serde: PyAnySerdeType,
        obs_serde: PyAnySerdeType,
        reward_serde: PyAnySerdeType,
        obs_space_serde: PyAnySerdeType,
        action_space_serde: PyAnySerdeType,
        shared_info_serde_option: PyAnySerdeType | None,
        shared_info_setter_serde_option: PyAnySerdeType | None,
        state_serde_option: PyAnySerdeType | None,
        recalculate_agent_id_every_step: builtins.bool,
        flinks_folder: builtins.str,
        min_process_steps_per_inference: builtins.int,
    ) -> EnvProcessInterface: ...
    def init_processes(
        self,
        proc_package_defs: collections.abc.Sequence[
            tuple[typing.Any, typing.Any, typing.Any, builtins.str]
        ],
    ) -> tuple[typing.Any, typing.Any]: ...
    def add_process(
        self, proc_package_def: tuple[typing.Any, typing.Any, typing.Any, builtins.str]
    ) -> None: ...
    def delete_process(self) -> None: ...
    def increase_min_process_steps_per_inference(self) -> builtins.int: ...
    def decrease_min_process_steps_per_inference(self) -> builtins.int: ...
    def cleanup(self) -> None: ...
    def collect_step_data(self) -> tuple[builtins.int, dict, dict, dict]: ...
    def send_env_actions(
        self, env_actions: collections.abc.Mapping[builtins.str, EnvAction]
    ) -> None: ...

@typing.final
class GameConfigPythonSerde:
    def __new__(cls) -> GameConfigPythonSerde: ...
    def __getstate__(self) -> builtins.list[builtins.int]: ...
    def __setstate__(self, _state: collections.abc.Sequence[builtins.int]) -> None: ...
    def append(
        self,
        buf: typing.Any,
        offset: builtins.int,
        obj: rlgym.rocket_league.api.GameConfig,
    ) -> builtins.int: ...
    def get_bytes(
        self, start_addr: builtins.int, obj: rlgym.rocket_league.api.GameConfig
    ) -> bytes: ...
    def retrieve(
        self, buf: typing.Any, offset: builtins.int
    ) -> tuple[rlgym.rocket_league.api.GameConfig, builtins.int]: ...

@typing.final
class GameStatePythonSerde:
    def __new__(
        cls, *args: typing.Any, agent_id_serde_type: PyAnySerdeType | None = None
    ) -> GameStatePythonSerde: ...
    def __getstate__(self) -> builtins.list[builtins.int]: ...
    def __setstate__(self, state: collections.abc.Sequence[builtins.int]) -> None: ...
    def append(
        self,
        buf: typing.Any,
        offset: builtins.int,
        obj: rlgym.rocket_league.api.GameState[rlgym.api.AgentID],
    ) -> builtins.int: ...
    def get_bytes(
        self,
        start_addr: builtins.int | None,
        obj: rlgym.rocket_league.api.GameState[rlgym.api.AgentID],
    ) -> bytes: ...
    def retrieve(
        self, buf: typing.Any, offset: builtins.int
    ) -> tuple[rlgym.rocket_league.api.GameState[rlgym.api.AgentID], builtins.int]: ...

class InitStrategy:
    @typing.final
    class ALL(InitStrategy):
        __match_args__ = ()
        def __new__(cls) -> InitStrategy.ALL: ...

    @typing.final
    class SOME(InitStrategy):
        __match_args__ = ("kwargs",)
        @property
        def kwargs(self) -> builtins.list[builtins.str]: ...
        def __new__(
            cls, kwargs: collections.abc.Sequence[builtins.str]
        ) -> InitStrategy.SOME: ...

    @typing.final
    class NONE(InitStrategy):
        __match_args__ = ()
        def __new__(cls) -> InitStrategy.NONE: ...

    ...

class NumpySerdeConfig:
    @typing.final
    class DYNAMIC(NumpySerdeConfig):
        __match_args__ = (
            "preprocessor_fn",
            "postprocessor_fn",
        )
        @property
        def preprocessor_fn(self) -> typing.Any | None: ...
        @property
        def postprocessor_fn(self) -> typing.Any | None: ...
        def __new__(
            cls,
            preprocessor_fn: typing.Any | None = None,
            postprocessor_fn: typing.Any | None = None,
        ) -> NumpySerdeConfig.DYNAMIC: ...

    @typing.final
    class STATIC(NumpySerdeConfig):
        __match_args__ = (
            "shape",
            "preprocessor_fn",
            "postprocessor_fn",
            "allocation_pool_min_size",
            "allocation_pool_max_size",
            "allocation_pool_warning_size",
        )
        @property
        def shape(self) -> builtins.list[builtins.int]: ...
        @property
        def preprocessor_fn(self) -> typing.Any | None: ...
        @property
        def postprocessor_fn(self) -> typing.Any | None: ...
        @property
        def allocation_pool_min_size(self) -> builtins.int: ...
        @property
        def allocation_pool_max_size(self) -> builtins.int | None: ...
        @property
        def allocation_pool_warning_size(self) -> builtins.int | None: ...
        def __new__(
            cls,
            shape: collections.abc.Sequence[builtins.int],
            preprocessor_fn: typing.Any | None = None,
            postprocessor_fn: typing.Any | None = None,
            allocation_pool_min_size: builtins.int = 0,
            allocation_pool_max_size: builtins.int | None = None,
            allocation_pool_warning_size: builtins.int | None = 10000,
        ) -> NumpySerdeConfig.STATIC: ...

    ...

@typing.final
class PhysicsObjectPythonSerde:
    def __new__(cls) -> PhysicsObjectPythonSerde: ...
    def __getstate__(self) -> builtins.list[builtins.int]: ...
    def __setstate__(self, _state: collections.abc.Sequence[builtins.int]) -> None: ...
    def append(
        self,
        buf: typing.Any,
        offset: builtins.int,
        obj: rlgym.rocket_league.api.PhysicsObject,
    ) -> builtins.int: ...
    def get_bytes(
        self, start_addr: builtins.int, obj: rlgym.rocket_league.api.PhysicsObject
    ) -> bytes: ...
    def retrieve(
        self, buf: typing.Any, offset: builtins.int
    ) -> tuple[rlgym.rocket_league.api.PhysicsObject, builtins.int]: ...

@typing.final
class PickleableInitStrategy:
    @typing.overload
    def __new__(cls) -> PickleableInitStrategy:
        r"""
        Create an uninitialized instance (should not be used except by unpicklers)
        """
    @typing.overload
    def __new__(cls, init_strategy: InitStrategy, /) -> PickleableInitStrategy:
        r"""
        Create a pickleable version of the provided InitStrategy class instance.
        """
    def __getstate__(self) -> builtins.list[builtins.int]: ...
    def __setstate__(self, state: collections.abc.Sequence[builtins.int]) -> None: ...

@typing.final
class PickleableNumpySerdeConfig:
    @typing.overload
    def __new__(cls) -> PickleableNumpySerdeConfig:
        r"""
        Create an uninitialized instance (should not be used except by unpicklers)
        """
    @typing.overload
    def __new__(cls, config: NumpySerdeConfig, /) -> PickleableNumpySerdeConfig:
        r"""
        Create a pickleable version of the provided NumpySerdeConfig class instance.
        """
    def __getstate__(self) -> builtins.list[builtins.int]: ...
    def __setstate__(self, state: collections.abc.Sequence[builtins.int]) -> None: ...

@typing.final
class PickleablePyAnySerdeType:
    @typing.overload
    def __new__(cls) -> PickleablePyAnySerdeType:
        r"""
        Create an uninitialized instance (should not be used except by unpicklers)
        """
    @typing.overload
    def __new__(cls, serde_type: PyAnySerdeType, /) -> PickleablePyAnySerdeType:
        r"""
        Create a pickleable version of the provided PyAnySerdeType class instance.
        """
    def __getstate__(self) -> builtins.list[builtins.int]: ...
    def __setstate__(self, state: collections.abc.Sequence[builtins.int]) -> None: ...

class PyAnySerdeType:
    def as_pickleable(self) -> typing.Any: ...
    @classmethod
    def __get_pydantic_core_schema__(
        cls, _source_type: typing.Any, handler: typing.Any
    ) -> typing.Any: ...
    def to_json(self) -> typing.Any: ...
    @typing.final
    class BOOL(PyAnySerdeType):
        __match_args__ = ()
        def __new__(cls) -> PyAnySerdeType.BOOL: ...

    @typing.final
    class BYTES(PyAnySerdeType):
        __match_args__ = ()
        def __new__(cls) -> PyAnySerdeType.BYTES: ...

    @typing.final
    class COMPLEX(PyAnySerdeType):
        __match_args__ = ()
        def __new__(cls) -> PyAnySerdeType.COMPLEX: ...

    @typing.final
    class DATACLASS(PyAnySerdeType):
        __match_args__ = (
            "clazz",
            "init_strategy",
            "field_serde_type_dict",
        )
        @property
        def clazz(self) -> typing.Any: ...
        @property
        def init_strategy(self) -> InitStrategy: ...
        @property
        def field_serde_type_dict(
            self,
        ) -> builtins.dict[builtins.str, PyAnySerdeType]: ...
        def __new__(
            cls,
            clazz: typing.Any,
            init_strategy: InitStrategy,
            field_serde_type_dict: collections.abc.Mapping[
                builtins.str, PyAnySerdeType
            ],
        ) -> PyAnySerdeType.DATACLASS: ...

    @typing.final
    class DICT(PyAnySerdeType):
        __match_args__ = (
            "keys_serde_type",
            "values_serde_type",
        )
        @property
        def keys_serde_type(self) -> PyAnySerdeType: ...
        @property
        def values_serde_type(self) -> PyAnySerdeType: ...
        def __new__(
            cls, keys_serde_type: PyAnySerdeType, values_serde_type: PyAnySerdeType
        ) -> PyAnySerdeType.DICT: ...

    @typing.final
    class DYNAMIC(PyAnySerdeType):
        __match_args__ = ()
        def __new__(cls) -> PyAnySerdeType.DYNAMIC: ...

    @typing.final
    class FLOAT(PyAnySerdeType):
        __match_args__ = ()
        def __new__(cls) -> PyAnySerdeType.FLOAT: ...

    @typing.final
    class INT(PyAnySerdeType):
        __match_args__ = ()
        def __new__(cls) -> PyAnySerdeType.INT: ...

    @typing.final
    class LIST(PyAnySerdeType):
        __match_args__ = ("items_serde_type",)
        @property
        def items_serde_type(self) -> PyAnySerdeType: ...
        def __new__(cls, items_serde_type: PyAnySerdeType) -> PyAnySerdeType.LIST: ...

    @typing.final
    class NUMPY(PyAnySerdeType):
        __match_args__ = (
            "dtype",
            "config",
        )
        @property
        def dtype(self) -> numpy.typing.DTypeLike: ...
        @property
        def config(self) -> NumpySerdeConfig: ...
        def __new__(
            cls, dtype: numpy.typing.DTypeLike, config: NumpySerdeConfig = ...
        ) -> PyAnySerdeType.NUMPY: ...

    @typing.final
    class OPTION(PyAnySerdeType):
        __match_args__ = ("value_serde_type",)
        @property
        def value_serde_type(self) -> PyAnySerdeType: ...
        def __new__(cls, value_serde_type: PyAnySerdeType) -> PyAnySerdeType.OPTION: ...

    @typing.final
    class PICKLE(PyAnySerdeType):
        __match_args__ = ()
        def __new__(cls) -> PyAnySerdeType.PICKLE: ...

    @typing.final
    class PYTHONSERDE(PyAnySerdeType):
        __match_args__ = ("python_serde",)
        @property
        def python_serde(self) -> typing.Any: ...
        def __new__(cls, python_serde: typing.Any) -> PyAnySerdeType.PYTHONSERDE: ...

    @typing.final
    class SET(PyAnySerdeType):
        __match_args__ = ("items_serde_type",)
        @property
        def items_serde_type(self) -> PyAnySerdeType: ...
        def __new__(cls, items_serde_type: PyAnySerdeType) -> PyAnySerdeType.SET: ...

    @typing.final
    class STRING(PyAnySerdeType):
        __match_args__ = ()
        def __new__(cls) -> PyAnySerdeType.STRING: ...

    @typing.final
    class TUPLE(PyAnySerdeType):
        __match_args__ = ("item_serde_types",)
        @property
        def item_serde_types(self) -> builtins.list[PyAnySerdeType]: ...
        def __new__(
            cls, item_serde_types: collections.abc.Sequence[PyAnySerdeType]
        ) -> PyAnySerdeType.TUPLE: ...

    @typing.final
    class TYPEDDICT(PyAnySerdeType):
        __match_args__ = ("key_serde_type_dict",)
        @property
        def key_serde_type_dict(
            self,
        ) -> builtins.dict[builtins.str, PyAnySerdeType]: ...
        def __new__(
            cls,
            key_serde_type_dict: collections.abc.Mapping[builtins.str, PyAnySerdeType],
        ) -> PyAnySerdeType.TYPEDDICT: ...

    @typing.final
    class UNION(PyAnySerdeType):
        __match_args__ = (
            "option_serde_types",
            "option_choice_fn",
        )
        @property
        def option_serde_types(self) -> builtins.list[PyAnySerdeType]: ...
        @property
        def option_choice_fn(self) -> typing.Callable[[typing.Any], int]: ...
        def __new__(
            cls,
            option_serde_types: collections.abc.Sequence[PyAnySerdeType],
            option_choice_fn: typing.Callable[[typing.Any], int],
        ) -> PyAnySerdeType.UNION: ...

@typing.final
class Timestep:
    @property
    def env_id(self) -> builtins.str: ...
    @property
    def timestep_id(self) -> builtins.int: ...
    @property
    def previous_timestep_id(self) -> builtins.int | None: ...
    @property
    def agent_id(self) -> typing.Any: ...
    @property
    def obs(self) -> typing.Any: ...
    @property
    def next_obs(self) -> typing.Any: ...
    @property
    def action(self) -> typing.Any: ...
    @property
    def reward(self) -> typing.Any: ...
    @property
    def terminated(self) -> builtins.bool: ...
    @property
    def truncated(self) -> builtins.bool: ...
    def __new__(
        cls,
        env_id: builtins.str,
        timestep_id: builtins.int,
        previous_timestep_id: builtins.int | None,
        agent_id: typing.Any,
        obs: typing.Any,
        next_obs: typing.Any,
        action: typing.Any,
        reward: typing.Any,
        terminated: builtins.bool,
        truncated: builtins.bool,
    ) -> Timestep: ...

@typing.final
class EnvActionResponseType(enum.Enum):
    STEP = ...
    RESET = ...
    SET_STATE = ...

def env_process_fn(
    proc_id: builtins.str,
    child_end: typing.Any,
    parent_sockname: typing.Any,
    build_env_fn: typing.Any,
    flinks_folder: builtins.str,
    shm_buffer_size: builtins.int,
    agent_id_serde: PyAnySerdeType,
    action_serde: PyAnySerdeType,
    obs_serde: PyAnySerdeType,
    reward_serde: PyAnySerdeType,
    obs_space_serde: PyAnySerdeType,
    action_space_serde: PyAnySerdeType,
    shared_info_serde_option: PyAnySerdeType | None,
    shared_info_setter_serde_option: PyAnySerdeType | None,
    state_serde_option: PyAnySerdeType | None,
    render: builtins.bool = False,
    render_delay_option: datetime.timedelta | None = None,
    recalculate_agent_id_every_step: builtins.bool = False,
) -> None: ...
def euler_to_quaternion(
    euler: numpy.typing.NDArray[numpy.float32],
) -> numpy.typing.NDArray[numpy.float32]: ...
def euler_to_rotation(
    euler: numpy.typing.NDArray[numpy.float32],
) -> numpy.typing.NDArray[numpy.float32]: ...
def quaternion_to_euler(
    quat: numpy.typing.NDArray[numpy.float32],
) -> numpy.typing.NDArray[numpy.float32]: ...
def quaternion_to_rotation(
    quat: numpy.typing.NDArray[numpy.float32],
) -> numpy.typing.NDArray[numpy.float32]: ...
def recvfrom_byte(socket: typing.Any) -> typing.Any: ...
def rotation_to_euler(
    rot: numpy.typing.NDArray[numpy.float32],
) -> numpy.typing.NDArray[numpy.float32]: ...
def rotation_to_quaternion(
    rot: numpy.typing.NDArray[numpy.float32],
) -> numpy.typing.NDArray[numpy.float32]: ...
def sendto_byte(socket: typing.Any, address: typing.Any) -> None: ...
